# Ejercicio 1: Clasificación de edad

**Enunciado:** determinar si una persona es niño, adolescente, adulto o adulto mayor según su edad.

**Lógica:** se define una edad directamente en el código y se evalúa usando condiciones `if`, `elif` y `else`. El primer rango que se cumple determina la categoría correspondiente.

In [1]:
def clasificar_edad(edad):
    if edad < 13:
        return "Niño"
    elif edad <= 17:
        return "Adolescente"
    elif edad <= 59:
        return "Adulto"
    else:
        return "Adulto mayor"


edad = 21
categoria = clasificar_edad(edad)

print(f"Edad: {edad} años")
print(f"Categoría: {categoria}")

Edad: 21 años
Categoría: Adulto

# Ejercicio 2: Conversor de temperatura

**Enunciado:** convertir una temperatura de grados Celsius a Fahrenheit utilizando la fórmula correspondiente.

**Lógica:** se define una temperatura en grados Celsius directamente en el código. Luego se aplica la fórmula de conversión `F = (C × 9/5) + 32` para obtener la temperatura equivalente en grados Fahrenheit y se muestra el resultado con un mensaje claro.

In [2]:
def convertir_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit


temperatura_celsius = 25
temperatura_fahrenheit = convertir_fahrenheit(temperatura_celsius)

print(f"Temperatura en Celsius: {temperatura_celsius} °C")
print(f"Temperatura en Fahrenheit: {temperatura_fahrenheit} °F")

Temperatura en Celsius: 25 °C
Temperatura en Fahrenheit: 77.0 °F

# Ejercicio 3: Calculadora básica

**Enunciado:** realizar una operación matemática entre dos números. Las operaciones permitidas son suma, resta, multiplicación y división. Además, se debe validar que no se intente dividir entre cero.

**Lógica:** se definen dos números y una operación matemática directamente en el código. Mediante una estructura `if`, `elif` y `else` se identifica la operación seleccionada y se ejecuta el cálculo correspondiente. En el caso de la división, se verifica previamente que el segundo número no sea cero para evitar errores.

In [3]:
def calculadora(numero1, numero2, operacion):
    if operacion == "suma":
        return numero1 + numero2

    elif operacion == "resta":
        return numero1 - numero2

    elif operacion == "multiplicacion":
        return numero1 * numero2

    elif operacion == "division":
        if numero2 == 0:
            return "Error: no se puede dividir entre cero"
        return numero1 / numero2

    else:
        return "Operación no válida"


numero1 = 20
numero2 = 5
operacion = "division"

resultado = calculadora(numero1, numero2, operacion)

print(f"Número 1: {numero1}")
print(f"Número 2: {numero2}")
print(f"Operación: {operacion}")
print(f"Resultado: {resultado}")

Número 1: 20
Número 2: 5
Operación: division
Resultado: 4.0

# Ejercicio 4: Número par o impar

**Enunciado:** determinar si un número entero es par o impar.

**Lógica:** se define un número entero directamente en el código. Utilizando el operador módulo `%`, se verifica si el residuo de la división entre 2 es igual a cero. Si se cumple, el número es par; de lo contrario, es impar.

In [4]:
def determinar_par_impar(numero):
    if numero % 2 == 0:
        return "Par"
    else:
        return "Impar"


numero = 15
resultado = determinar_par_impar(numero)

print(f"Número: {numero}")
print(f"Resultado: {resultado}")

Número: 15
Resultado: Impar

# Ejercicio 5: Tabla de multiplicar

**Enunciado:** mostrar la tabla de multiplicar de un número entero desde el 1 hasta el 12 utilizando un ciclo.

**Lógica:** se define un número entero directamente en el código. Luego se utiliza un ciclo `for` para recorrer los números del 1 al 12 y multiplicarlos por el número seleccionado. En cada iteración se muestra el resultado correspondiente de la tabla de multiplicar.

In [5]:
numero = 7

print(f"Tabla de multiplicar del {numero}")
print("-" * 25)

for i in range(1, 13):
    resultado = numero * i
    print(f"{numero} x {i} = {resultado}")

Tabla de multiplicar del 7
-------------------------
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70
7 x 11 = 77
7 x 12 = 84

# Ejercicio 6: Contador de vocales

**Enunciado:** contar cuántas vocales contiene una frase. El programa debe funcionar correctamente tanto con letras mayúsculas como minúsculas.

**Lógica:** se define una frase directamente en el código. Luego se convierte a minúsculas para facilitar la comparación y se recorre cada carácter utilizando un ciclo `for`. Si el carácter corresponde a una vocal (a, e, i, o, u), se incrementa un contador. Finalmente, se muestra la cantidad total de vocales encontradas.

In [6]:
frase = "Python es un lenguaje Muy Utilizado en Big Data"

contador_vocales = 0

for letra in frase.lower():
    if letra in "aeiou":
        contador_vocales += 1

print(f"Frase: {frase}")
print(f"Cantidad de vocales: {contador_vocales}")

Frase: Python es un lenguaje Muy Utilizado en Big Data
Cantidad de vocales: 17

# Ejercicio 7: Promedio de calificaciones

**Enunciado:** calcular la suma total y el promedio de cinco calificaciones. Además, determinar si el estudiante aprobó o reprobó considerando que la nota mínima para aprobar es 70.

**Lógica:** se define una lista con cinco calificaciones. Se utiliza la función `sum()` para obtener la suma total y `len()` para conocer la cantidad de elementos. El promedio se calcula dividiendo la suma entre la cantidad de calificaciones. Finalmente, mediante una condición `if` se determina si el estudiante aprobó o reprobó según el promedio obtenido.

In [7]:
calificaciones = [85, 90, 78, 88, 92]

suma_total = sum(calificaciones)
promedio = suma_total / len(calificaciones)

if promedio >= 70:
    estado = "Aprobado"
else:
    estado = "Reprobado"

print(f"Calificaciones: {calificaciones}")
print(f"Suma total: {suma_total}")
print(f"Promedio: {promedio:.2f}")
print(f"Estado: {estado}")

Calificaciones: [85, 90, 78, 88, 92]
Suma total: 433
Promedio: 86.60
Estado: Aprobado

# Ejercicio 8: Lista de números positivos y negativos

**Enunciado:** contar cuántos números positivos, negativos y ceros existen dentro de una lista de diez números.

**Lógica:** se define una lista con diez números enteros. Mediante un ciclo `for`, se recorre cada elemento de la lista y se evalúa si es mayor que cero, menor que cero o igual a cero. Dependiendo del caso, se incrementa el contador correspondiente. Al finalizar, se muestra un resumen con la cantidad de números positivos, negativos y ceros encontrados.

In [8]:
numeros = [15, -8, 0, 23, -12, 7, 0, -3, 18, -5]

positivos = 0
negativos = 0
ceros = 0

for numero in numeros:
    if numero > 0:
        positivos += 1
    elif numero < 0:
        negativos += 1
    else:
        ceros += 1

print(f"Lista de números: {numeros}")
print(f"Cantidad de positivos: {positivos}")
print(f"Cantidad de negativos: {negativos}")
print(f"Cantidad de ceros: {ceros}")

Lista de números: [15, -8, 0, 23, -12, 7, 0, -3, 18, -5]
Cantidad de positivos: 4
Cantidad de negativos: 4
Cantidad de ceros: 2

# Ejercicio 9: Mayor y menor de una lista

**Enunciado:** encontrar el número mayor y el número menor dentro de una lista de números enteros. Además, calcular la diferencia entre ambos valores y explicar el uso de las funciones `max()` y `min()`.

**Lógica:** se define una lista con varios números enteros. Se utiliza la función `max()` para obtener el valor más grande de la lista y la función `min()` para obtener el valor más pequeño. Posteriormente se calcula la diferencia entre ambos valores mediante una resta y se muestran los resultados.

In [9]:
numeros = [45, 12, 78, 34, 99, 23, 67, 5, 81, 56]

numero_mayor = max(numeros)
numero_menor = min(numeros)

diferencia = numero_mayor - numero_menor

print(f"Lista de números: {numeros}")
print(f"Número mayor: {numero_mayor}")
print(f"Número menor: {numero_menor}")
print(f"Diferencia entre mayor y menor: {diferencia}")

Lista de números: [45, 12, 78, 34, 99, 23, 67, 5, 81, 56]
Número mayor: 99
Número menor: 5
Diferencia entre mayor y menor: 94

# Ejercicio 10: Diccionario de estudiante

**Enunciado:** crear un diccionario que almacene información de un estudiante, incluyendo nombre, edad, carrera, promedio y estado. Posteriormente, mostrar los datos de forma ordenada y explicar cómo acceder a los valores almacenados.

**Lógica:** se crea un diccionario llamado `estudiante` que contiene diferentes pares clave-valor. Cada clave representa un dato específico del estudiante y su valor contiene la información correspondiente. Para mostrar los datos, se accede a cada valor utilizando el nombre de la clave entre corchetes.

In [10]:
estudiante = {
    "nombre": "David Alejandro Carcamo Espinal",
    "edad": 23,
    "carrera": "Ingeniería en Ciencias de la Computación",
    "promedio": 88.5,
    "estado": "Aprobado"
}

print("DATOS DEL ESTUDIANTE")
print("-" * 30)

print(f"Nombre: {estudiante['nombre']}")
print(f"Edad: {estudiante['edad']} años")
print(f"Carrera: {estudiante['carrera']}")
print(f"Promedio: {estudiante['promedio']}")
print(f"Estado: {estudiante['estado']}")

DATOS DEL ESTUDIANTE
------------------------------
Nombre: David Alejandro Carcamo Espinal
Edad: 23 años
Carrera: Ingeniería en Ciencias de la Computación
Promedio: 88.5
Estado: Aprobado

# Ejercicio 11: Función para calcular descuento

**Enunciado:** crear una función llamada `calcular_descuento` que reciba el precio original de un producto y el porcentaje de descuento. La función debe calcular y retornar el precio final después de aplicar el descuento.

**Lógica:** se crea una función que recibe dos parámetros: el precio original y el porcentaje de descuento. Primero se calcula el valor del descuento y luego se resta al precio original para obtener el precio final. Finalmente, la función retorna el resultado para ser utilizado fuera de ella.

**Datos de entrada:** precio original y porcentaje de descuento.

**Dato de salida:** precio final después de aplicar el descuento.

In [11]:
def calcular_descuento(precio_original, porcentaje_descuento):
    descuento = precio_original * (porcentaje_descuento / 100)
    precio_final = precio_original - descuento
    return precio_final


precio = 1500
descuento = 20

precio_final = calcular_descuento(precio, descuento)

print(f"Precio original: L. {precio}")
print(f"Descuento aplicado: {descuento}%")
print(f"Precio final: L. {precio_final}")

Precio original: L. 1500
Descuento aplicado: 20%
Precio final: L. 1200.0

# Ejercicio 12: Validación de contraseña

**Enunciado:** validar si una contraseña cumple con los requisitos mínimos de seguridad. Debe tener al menos 8 caracteres, contener al menos un número, una letra mayúscula y una letra minúscula.

**Lógica:** se define una contraseña directamente en el código. Luego se verifica cada requisito utilizando funciones y expresiones de Python. Se comprueba la longitud de la contraseña, la existencia de números, letras mayúsculas y letras minúsculas. Si cumple todas las condiciones, la contraseña se considera válida; de lo contrario, se indica que no es válida.

In [12]:
contrasena = "BigData2025"

tiene_longitud = len(contrasena) >= 8
tiene_numero = any(caracter.isdigit() for caracter in contrasena)
tiene_mayuscula = any(caracter.isupper() for caracter in contrasena)
tiene_minuscula = any(caracter.islower() for caracter in contrasena)

if tiene_longitud and tiene_numero and tiene_mayuscula and tiene_minuscula:
    resultado = "Contraseña válida"
else:
    resultado = "Contraseña no válida"

print(f"Contraseña evaluada: {contrasena}")
print(resultado)

Contraseña evaluada: BigData2025
Contraseña válida

# Ejercicio 13: Sistema simple de inventario

**Enunciado:** crear un sistema simple de inventario que almacene productos con código, nombre, precio y cantidad disponible. Mostrar todos los productos, buscar un producto por código y calcular el valor total del inventario.

**Lógica:** se utiliza una lista de diccionarios para almacenar la información de cada producto. Primero se muestran todos los productos registrados. Luego se busca un producto utilizando su código. Finalmente, se calcula el valor total del inventario multiplicando el precio por la cantidad disponible de cada producto y sumando todos los resultados.

In [13]:
productos = [
    {"codigo": "P001", "nombre": "Laptop", "precio": 18000, "cantidad": 5},
    {"codigo": "P002", "nombre": "Mouse", "precio": 350, "cantidad": 20},
    {"codigo": "P003", "nombre": "Teclado", "precio": 800, "cantidad": 10},
    {"codigo": "P004", "nombre": "Monitor", "precio": 4500, "cantidad": 8}
]

print("LISTA DE PRODUCTOS")
print("-" * 60)

for producto in productos:
    print(
        f"Código: {producto['codigo']} | "
        f"Nombre: {producto['nombre']} | "
        f"Precio: L. {producto['precio']} | "
        f"Cantidad: {producto['cantidad']}"
    )

codigo_buscar = "P003"

print("\nBÚSQUEDA DE PRODUCTO")
print("-" * 60)

for producto in productos:
    if producto["codigo"] == codigo_buscar:
        print(
            f"Producto encontrado: {producto['nombre']} "
            f"(Precio: L. {producto['precio']}, "
            f"Cantidad: {producto['cantidad']})"
        )

valor_total = 0

for producto in productos:
    valor_total += producto["precio"] * producto["cantidad"]

print("\nVALOR TOTAL DEL INVENTARIO")
print("-" * 60)
print(f"L. {valor_total}")

LISTA DE PRODUCTOS
------------------------------------------------------------
Código: P001 | Nombre: Laptop | Precio: L. 18000 | Cantidad: 5
Código: P002 | Nombre: Mouse | Precio: L. 350 | Cantidad: 20
Código: P003 | Nombre: Teclado | Precio: L. 800 | Cantidad: 10
Código: P004 | Nombre: Monitor | Precio: L. 4500 | Cantidad: 8

BÚSQUEDA DE PRODUCTO
------------------------------------------------------------
Producto encontrado: Teclado (Precio: L. 800, Cantidad: 10)

VALOR TOTAL DEL INVENTARIO
------------------------------------------------------------
L. 141000

# Ejercicio 14: Registro de ventas

**Enunciado:** crear un registro de ventas donde cada venta tenga cliente, producto, cantidad y precio unitario. Calcular el total por cada venta, el total general vendido e identificar el cliente con la compra más alta.

**Lógica:** se utiliza una lista de diccionarios para almacenar las ventas. Cada diccionario representa una venta con su cliente, producto, cantidad y precio unitario. Luego se recorre la lista para calcular el total de cada venta multiplicando la cantidad por el precio unitario. También se acumula el total general vendido y se identifica la venta con el monto más alto.

In [14]:
ventas = [
    {"cliente": "Carlos Méndez", "producto": "Laptop", "cantidad": 1, "precio_unitario": 18000},
    {"cliente": "María López", "producto": "Mouse", "cantidad": 3, "precio_unitario": 350},
    {"cliente": "Ana Rodríguez", "producto": "Monitor", "cantidad": 2, "precio_unitario": 4500},
    {"cliente": "José Martínez", "producto": "Teclado", "cantidad": 4, "precio_unitario": 800}
]

total_general = 0
compra_mas_alta = ventas[0]

print("REGISTRO DE VENTAS")
print("-" * 70)

for venta in ventas:
    total_venta = venta["cantidad"] * venta["precio_unitario"]
    venta["total"] = total_venta
    total_general += total_venta

    if total_venta > compra_mas_alta["cantidad"] * compra_mas_alta["precio_unitario"]:
        compra_mas_alta = venta

    print(
        f"Cliente: {venta['cliente']} | "
        f"Producto: {venta['producto']} | "
        f"Cantidad: {venta['cantidad']} | "
        f"Precio unitario: L. {venta['precio_unitario']} | "
        f"Total: L. {total_venta}"
    )

print("\nTOTAL GENERAL VENDIDO")
print("-" * 70)
print(f"L. {total_general}")

print("\nCLIENTE CON LA COMPRA MÁS ALTA")
print("-" * 70)
print(f"Cliente: {compra_mas_alta['cliente']}")
print(f"Producto: {compra_mas_alta['producto']}")
print(f"Total de compra: L. {compra_mas_alta['total']}")

REGISTRO DE VENTAS
----------------------------------------------------------------------
Cliente: Carlos Méndez | Producto: Laptop | Cantidad: 1 | Precio unitario: L. 18000 | Total: L. 18000
Cliente: María López | Producto: Mouse | Cantidad: 3 | Precio unitario: L. 350 | Total: L. 1050
Cliente: Ana Rodríguez | Producto: Monitor | Cantidad: 2 | Precio unitario: L. 4500 | Total: L. 9000
Cliente: José Martínez | Producto: Teclado | Cantidad: 4 | Precio unitario: L. 800 | Total: L. 3200

TOTAL GENERAL VENDIDO
----------------------------------------------------------------------
L. 31250

CLIENTE CON LA COMPRA MÁS ALTA
----------------------------------------------------------------------
Cliente: Carlos Méndez
Producto: Laptop
Total de compra: L. 18000

# Ejercicio 15: Limpieza básica de texto

**Enunciado:** realizar una limpieza básica de una frase eliminando espacios innecesarios, convirtiendo el texto a minúsculas, reemplazando espacios dobles por espacios simples y contando la cantidad de palabras contenidas en la frase.

**Lógica:** se define una frase con espacios adicionales al inicio, al final y entre algunas palabras. Posteriormente se aplican diferentes métodos de cadena para limpiar el texto. Primero se eliminan los espacios externos, luego se convierte el texto a minúsculas y se sustituyen los espacios dobles por espacios simples. Finalmente, se divide la frase en palabras para contabilizar cuántas contiene.

**Métodos utilizados:**

- `strip()`: elimina espacios en blanco al inicio y al final de una cadena.
- `lower()`: convierte todos los caracteres del texto a minúsculas.
- `replace()`: reemplaza una cadena por otra dentro del texto.
- `split()`: divide una cadena en una lista de palabras utilizando los espacios como separadores.

In [15]:
frase = "   Python   es  muy UTILIZADO en   Big Data   "

print("Texto original:")
print(f"'{frase}'")

texto_limpio = frase.strip()
texto_limpio = texto_limpio.lower()

while "  " in texto_limpio:
    texto_limpio = texto_limpio.replace("  ", " ")

palabras = texto_limpio.split()
cantidad_palabras = len(palabras)

print("\nTexto limpio:")
print(f"'{texto_limpio}'")

print(f"\nCantidad de palabras: {cantidad_palabras}")
print(f"Lista de palabras: {palabras}")

Texto original:
'   Python   es  muy UTILIZADO en   Big Data   '

Texto limpio:
'python es muy utilizado en big data'

Cantidad de palabras: 7
Lista de palabras: ['python', 'es', 'muy', 'utilizado', 'en', 'big', 'data']

# Ejercicio 16: DataFrame de estudiantes

**Enunciado:** crear un DataFrame con al menos 10 estudiantes. Debe incluir nombre, carrera, edad, promedio y ciudad. Luego se deben mostrar las primeras 5 filas, la información general del DataFrame, el promedio general, los estudiantes con promedio mayor o igual a 80 y ordenar los estudiantes por promedio de mayor a menor.

**Lógica:** se utiliza la librería `pandas` para crear una tabla de datos llamada DataFrame. Primero se define una lista de diccionarios con la información de los estudiantes. Luego se aplican métodos de pandas para visualizar, analizar, filtrar y ordenar la información.

In [1]:
import pandas as pd

estudiantes = [
    {"Nombre": "David Carcamo", "Carrera": "Ingeniería en Computación", "Edad": 23, "Promedio": 88, "Ciudad": "Tegucigalpa"},
    {"Nombre": "María López", "Carrera": "Administración", "Edad": 22, "Promedio": 91, "Ciudad": "San Pedro Sula"},
    {"Nombre": "Carlos Méndez", "Carrera": "Contaduría", "Edad": 24, "Promedio": 76, "Ciudad": "La Ceiba"},
    {"Nombre": "Ana Rodríguez", "Carrera": "Ingeniería Industrial", "Edad": 21, "Promedio": 84, "Ciudad": "Choluteca"},
    {"Nombre": "Luis Martínez", "Carrera": "Derecho", "Edad": 25, "Promedio": 69, "Ciudad": "Juticalpa"},
    {"Nombre": "Sofía Hernández", "Carrera": "Mercadotecnia", "Edad": 22, "Promedio": 95, "Ciudad": "Comayagua"},
    {"Nombre": "Pedro Castillo", "Carrera": "Ingeniería en Computación", "Edad": 23, "Promedio": 80, "Ciudad": "Danlí"},
    {"Nombre": "Lucía Torres", "Carrera": "Psicología", "Edad": 21, "Promedio": 73, "Ciudad": "Tegucigalpa"},
    {"Nombre": "José Rivera", "Carrera": "Arquitectura", "Edad": 24, "Promedio": 86, "Ciudad": "Siguatepeque"},
    {"Nombre": "Gabriela Flores", "Carrera": "Medicina", "Edad": 22, "Promedio": 92, "Ciudad": "El Progreso"}
]

df_estudiantes = pd.DataFrame(estudiantes)

print("Primeras 5 filas del DataFrame:")
display(df_estudiantes.head())

print("\nInformación general del DataFrame:")
df_estudiantes.info()

promedio_general = df_estudiantes["Promedio"].mean()
print(f"\nPromedio general de calificaciones: {promedio_general:.2f}")

print("\nEstudiantes con promedio mayor o igual a 80:")
display(df_estudiantes[df_estudiantes["Promedio"] >= 80])

print("\nEstudiantes ordenados por promedio de mayor a menor:")
display(df_estudiantes.sort_values(by="Promedio", ascending=False))

Primeras 5 filas del DataFrame:

          Nombre                    Carrera  Edad  Promedio          Ciudad
0  David Carcamo  Ingeniería en Computación    23        88     Tegucigalpa
1    María López             Administración    22        91  San Pedro Sula
2  Carlos Méndez                 Contaduría    24        76        La Ceiba
3  Ana Rodríguez      Ingeniería Industrial    21        84       Choluteca
4  Luis Martínez                    Derecho    25        69       Juticalpa

Información general del DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    10 non-null     str
 1   Carrera   10 non-null     str
 2   Edad      10 non-null     int64
 3   Promedio  10 non-null     int64
 4   Ciudad    10 non-null     str
dtypes: int64(2), str(3)
memory usage: 924.0 bytes

Promedio general de calificaciones: 83.40

Estudiantes con promedio mayor o igual a 80:

            Nombre                    Carrera  Edad  Promedio          Ciudad
0    David Carcamo  Ingeniería en Computación    23        88     Tegucigalpa
1      María López             Administración    22        91  San Pedro Sula
3    Ana Rodríguez      Ingeniería Industrial    21        84       Choluteca
5  Sofía Hernández              Mercadotecnia    22        95       Comayagua
6   Pedro Castillo  Ingeniería en Computación    23        80           Danlí
8      José Rivera               Arquitectura    24        86    Siguatepeque
9  Gabriela Flores                   Medicina    22        92     El Progreso

Estudiantes ordenados por promedio de mayor a menor:

            Nombre                    Carrera  Edad  Promedio          Ciudad
5  Sofía Hernández              Mercadotecnia    22        95       Comayagua
9  Gabriela Flores                   Medicina    22        92     El Progreso
1      María López             Administración    22        91  San Pedro Sula
0    David Carcamo  Ingeniería en Computación    23        88     Tegucigalpa
8      José Rivera               Arquitectura    24        86    Siguatepeque
3    Ana Rodríguez      Ingeniería Industrial    21        84       Choluteca
6   Pedro Castillo  Ingeniería en Computación    23        80           Danlí
2    Carlos Méndez                 Contaduría    24        76        La Ceiba
7     Lucía Torres                 Psicología    21        73     Tegucigalpa
4    Luis Martínez                    Derecho    25        69       Juticalpa

# Ejercicio 17: Análisis de ventas con pandas

**Enunciado:** crear un DataFrame de ventas con al menos 15 registros. Debe incluir fecha, vendedor, producto, categoría, cantidad y precio unitario. Posteriormente se debe calcular una nueva columna llamada TotalVenta, obtener el total vendido por vendedor, identificar el producto más vendido, la categoría con mayor ingreso y ordenar las ventas de mayor a menor.

**Lógica:** se crea un DataFrame utilizando pandas con información de ventas. Se calcula el valor total de cada venta multiplicando la cantidad por el precio unitario. Después se utilizan funciones de agrupación y agregación para obtener estadísticas de ventas por vendedor, producto y categoría. Finalmente, se ordenan los registros según el monto de venta.

In [2]:
import pandas as pd

ventas = [
    ["2025-01-05", "Carlos", "Laptop", "Tecnología", 1, 18000],
    ["2025-01-06", "María", "Mouse", "Accesorios", 3, 350],
    ["2025-01-07", "José", "Monitor", "Tecnología", 2, 4500],
    ["2025-01-08", "Ana", "Teclado", "Accesorios", 4, 800],
    ["2025-01-09", "Carlos", "Impresora", "Tecnología", 1, 6500],
    ["2025-01-10", "María", "Laptop", "Tecnología", 1, 18000],
    ["2025-01-11", "José", "Mouse", "Accesorios", 5, 350],
    ["2025-01-12", "Ana", "Monitor", "Tecnología", 1, 4500],
    ["2025-01-13", "Carlos", "Teclado", "Accesorios", 2, 800],
    ["2025-01-14", "María", "Impresora", "Tecnología", 1, 6500],
    ["2025-01-15", "José", "Laptop", "Tecnología", 1, 18000],
    ["2025-01-16", "Ana", "Mouse", "Accesorios", 4, 350],
    ["2025-01-17", "Carlos", "Monitor", "Tecnología", 1, 4500],
    ["2025-01-18", "María", "Teclado", "Accesorios", 3, 800],
    ["2025-01-19", "José", "Impresora", "Tecnología", 1, 6500]
]

df_ventas = pd.DataFrame(
    ventas,
    columns=["Fecha", "Vendedor", "Producto", "Categoria", "Cantidad", "PrecioUnitario"]
)

df_ventas["TotalVenta"] = df_ventas["Cantidad"] * df_ventas["PrecioUnitario"]

print("DataFrame de ventas:")
display(df_ventas)

print("\nTotal vendido por vendedor:")
display(df_ventas.groupby("Vendedor")["TotalVenta"].sum())

print("\nProducto más vendido (por cantidad):")
producto_mas_vendido = df_ventas.groupby("Producto")["Cantidad"].sum().idxmax()
print(producto_mas_vendido)

print("\nCategoría con mayor ingreso:")
categoria_mayor_ingreso = df_ventas.groupby("Categoria")["TotalVenta"].sum().idxmax()
print(categoria_mayor_ingreso)

print("\nVentas ordenadas de mayor a menor:")
display(df_ventas.sort_values(by="TotalVenta", ascending=False))

DataFrame de ventas:

,Fecha,Vendedor,Producto,Categoria,Cantidad,PrecioUnitario,TotalVenta
0,2025-01-05,Carlos,Laptop,Tecnología,1,18000,18000
1,2025-01-06,María,Mouse,Accesorios,3,350,1050
2,2025-01-07,José,Monitor,Tecnología,2,4500,9000
3,2025-01-08,Ana,Teclado,Accesorios,4,800,3200
4,2025-01-09,Carlos,Impresora,Tecnología,1,6500,6500
5,2025-01-10,María,Laptop,Tecnología,1,18000,18000
6,2025-01-11,José,Mouse,Accesorios,5,350,1750
7,2025-01-12,Ana,Monitor,Tecnología,1,4500,4500
8,2025-01-13,Carlos,Teclado,Accesorios,2,800,1600
9,2025-01-14,María,Impresora,Tecnología,1,6500,6500
10,2025-01-15,José,Laptop,Tecnología,1,18000,18000
11,2025-01-16,Ana,Mouse,Accesorios,4,350,1400
12,2025-01-17,Carlos,Monitor,Tecnología,1,4500,4500
13,2025-01-18,María,Teclado,Accesorios,3,800,2400
14,2025-01-19,José,Impresora,Tecnología,1,6500,6500

Total vendido por vendedor:

Vendedor
Ana        9100
Carlos    30600
José      35250
María     27950
Name: TotalVenta, dtype: int64

Producto más vendido (por cantidad):
Mouse

Categoría con mayor ingreso:
Tecnología

Ventas ordenadas de mayor a menor:

,Fecha,Vendedor,Producto,Categoria,Cantidad,PrecioUnitario,TotalVenta
0,2025-01-05,Carlos,Laptop,Tecnología,1,18000,18000
5,2025-01-10,María,Laptop,Tecnología,1,18000,18000
10,2025-01-15,José,Laptop,Tecnología,1,18000,18000
2,2025-01-07,José,Monitor,Tecnología,2,4500,9000
4,2025-01-09,Carlos,Impresora,Tecnología,1,6500,6500
9,2025-01-14,María,Impresora,Tecnología,1,6500,6500
14,2025-01-19,José,Impresora,Tecnología,1,6500,6500
12,2025-01-17,Carlos,Monitor,Tecnología,1,4500,4500
7,2025-01-12,Ana,Monitor,Tecnología,1,4500,4500
3,2025-01-08,Ana,Teclado,Accesorios,4,800,3200
13,2025-01-18,María,Teclado,Accesorios,3,800,2400
6,2025-01-11,José,Mouse,Accesorios,5,350,1750
8,2025-01-13,Carlos,Teclado,Accesorios,2,800,1600
11,2025-01-16,Ana,Mouse,Accesorios,4,350,1400
1,2025-01-06,María,Mouse,Accesorios,3,350,1050

# Ejercicio 18: Limpieza de datos con pandas

**Enunciado:** crear un DataFrame con información de clientes que contenga algunos datos incompletos. Posteriormente se deben identificar los valores nulos, contar cuántos existen por columna, reemplazar las ciudades vacías por "No especificada", eliminar los registros que no tengan correo electrónico y mostrar el DataFrame limpio.

**Lógica:** se crea un DataFrame con algunos valores faltantes utilizando `None`. Luego se emplean métodos de pandas para detectar y contabilizar los valores nulos. Después se reemplazan las ciudades vacías por un valor predeterminado y se eliminan los registros que no poseen correo electrónico. Finalmente se muestra el DataFrame resultante después de la limpieza.

In [3]:
import pandas as pd

clientes = {
    "Nombre": [
        "Carlos Méndez",
        "Ana López",
        "José Rivera",
        "María Torres",
        "Luis Martínez",
        "Sofía Hernández"
    ],
    "Edad": [25, 30, None, 28, 35, 22],
    "Correo": [
        "carlos@gmail.com",
        None,
        "jose@gmail.com",
        "maria@gmail.com",
        None,
        "sofia@gmail.com"
    ],
    "Ciudad": [
        "Tegucigalpa",
        "",
        "San Pedro Sula",
        None,
        "",
        "La Ceiba"
    ],
    "Telefono": [
        "9999-1111",
        None,
        "9888-2222",
        "9777-3333",
        None,
        "9666-4444"
    ]
}

df_clientes = pd.DataFrame(clientes)

print("DataFrame original:")
display(df_clientes)

print("\nValores nulos encontrados:")
display(df_clientes.isnull())

print("\nCantidad de valores nulos por columna:")
display(df_clientes.isnull().sum())

df_clientes["Ciudad"] = df_clientes["Ciudad"].replace("", "No especificada")
df_clientes["Ciudad"] = df_clientes["Ciudad"].fillna("No especificada")

df_clientes_limpio = df_clientes.dropna(subset=["Correo"])

print("\nDataFrame después de la limpieza:")
display(df_clientes_limpio)

DataFrame original:

            Nombre  Edad            Correo          Ciudad   Telefono
0    Carlos Méndez  25.0  carlos@gmail.com     Tegucigalpa  9999-1111
1        Ana López  30.0               NaN                        NaN
2      José Rivera   NaN    jose@gmail.com  San Pedro Sula  9888-2222
3     María Torres  28.0   maria@gmail.com             NaN  9777-3333
4    Luis Martínez  35.0               NaN                        NaN
5  Sofía Hernández  22.0   sofia@gmail.com        La Ceiba  9666-4444

Valores nulos encontrados:

   Nombre   Edad  Correo  Ciudad  Telefono
0   False  False   False   False     False
1   False  False    True   False      True
2   False   True   False   False     False
3   False  False   False    True     False
4   False  False    True   False      True
5   False  False   False   False     False

Cantidad de valores nulos por columna:

Nombre      0
Edad        1
Correo      2
Ciudad      1
Telefono    2
dtype: int64

DataFrame después de la limpieza:

            Nombre  Edad            Correo           Ciudad   Telefono
0    Carlos Méndez  25.0  carlos@gmail.com      Tegucigalpa  9999-1111
2      José Rivera   NaN    jose@gmail.com   San Pedro Sula  9888-2222
3     María Torres  28.0   maria@gmail.com  No especificada  9777-3333
5  Sofía Hernández  22.0   sofia@gmail.com         La Ceiba  9666-4444

# Ejercicio 19: Análisis de préstamos

**Enunciado:** crear un DataFrame con solicitudes de préstamo que incluya cliente, monto solicitado, plazo, ingreso mensual y estado de solicitud. Posteriormente se debe calcular el monto promedio solicitado, contar solicitudes por estado, mostrar únicamente los préstamos aprobados, identificar clientes con montos superiores a 50,000 y agrupar los datos por estado para calcular el promedio del monto solicitado.

**Lógica:** se crea un DataFrame utilizando pandas para almacenar información de solicitudes de préstamo. Luego se aplican funciones de análisis para obtener estadísticas generales, filtrar registros específicos y agrupar información según el estado de la solicitud.

In [4]:
import pandas as pd

prestamos = {
    "Cliente": [
        "Carlos Méndez",
        "Ana López",
        "José Rivera",
        "María Torres",
        "Luis Martínez",
        "Sofía Hernández",
        "Pedro Castillo",
        "Gabriela Flores"
    ],
    "MontoSolicitado": [
        25000,
        60000,
        45000,
        80000,
        30000,
        55000,
        70000,
        40000
    ],
    "PlazoMeses": [
        24,
        48,
        36,
        60,
        24,
        48,
        60,
        36
    ],
    "IngresoMensual": [
        18000,
        35000,
        22000,
        45000,
        20000,
        38000,
        50000,
        25000
    ],
    "EstadoSolicitud": [
        "Aprobado",
        "Aprobado",
        "Pendiente",
        "Aprobado",
        "Rechazado",
        "Pendiente",
        "Aprobado",
        "Rechazado"
    ]
}

df_prestamos = pd.DataFrame(prestamos)

print("DataFrame de préstamos:")
display(df_prestamos)

monto_promedio = df_prestamos["MontoSolicitado"].mean()
print(f"\nMonto promedio solicitado: L. {monto_promedio:,.2f}")

print("\nCantidad de solicitudes por estado:")
display(df_prestamos["EstadoSolicitud"].value_counts())

print("\nPréstamos aprobados:")
display(df_prestamos[df_prestamos["EstadoSolicitud"] == "Aprobado"])

print("\nClientes con monto solicitado mayor a L. 50,000:")
display(df_prestamos[df_prestamos["MontoSolicitado"] > 50000])

print("\nPromedio del monto solicitado por estado:")
display(
    df_prestamos.groupby("EstadoSolicitud")["MontoSolicitado"].mean()
)

DataFrame de préstamos:

,Cliente,MontoSolicitado,PlazoMeses,IngresoMensual,EstadoSolicitud
0,Carlos Méndez,25000,24,18000,Aprobado
1,Ana López,60000,48,35000,Aprobado
2,José Rivera,45000,36,22000,Pendiente
3,María Torres,80000,60,45000,Aprobado
4,Luis Martínez,30000,24,20000,Rechazado
5,Sofía Hernández,55000,48,38000,Pendiente
6,Pedro Castillo,70000,60,50000,Aprobado
7,Gabriela Flores,40000,36,25000,Rechazado

Monto promedio solicitado: L. 50,625.00

Cantidad de solicitudes por estado:

EstadoSolicitud
Aprobado     4
Pendiente    2
Rechazado    2
Name: count, dtype: int64

Préstamos aprobados:

          Cliente  MontoSolicitado  PlazoMeses  IngresoMensual EstadoSolicitud
0   Carlos Méndez            25000          24           18000        Aprobado
1       Ana López            60000          48           35000        Aprobado
3    María Torres            80000          60           45000        Aprobado
6  Pedro Castillo            70000          60           50000        Aprobado

Clientes con monto solicitado mayor a L. 50,000:

,Cliente,MontoSolicitado,PlazoMeses,IngresoMensual,EstadoSolicitud
1,Ana López,60000,48,35000,Aprobado
3,María Torres,80000,60,45000,Aprobado
5,Sofía Hernández,55000,48,38000,Pendiente
6,Pedro Castillo,70000,60,50000,Aprobado

Promedio del monto solicitado por estado:

EstadoSolicitud
Aprobado     58750.0
Pendiente    50000.0
Rechazado    35000.0
Name: MontoSolicitado, dtype: float64

# Ejercicio 20: Mini análisis de datos tipo empresa

**Enunciado:** crear un DataFrame con información de empleados que incluya nombre, departamento, cargo, salario, años de experiencia y ciudad. Posteriormente se deben mostrar los primeros registros, obtener estadísticas salariales, calcular el salario promedio por departamento, identificar al empleado con el salario más alto, mostrar empleados con más de 5 años de experiencia, ordenar los empleados por salario y crear una nueva columna llamada NivelExperiencia.

**Lógica:** se crea un DataFrame utilizando pandas para almacenar información de empleados. Después se aplican diferentes métodos de análisis para obtener estadísticas descriptivas, agrupar información por departamento, filtrar registros específicos y ordenar los datos. Finalmente, se crea una nueva columna que clasifica a cada empleado según sus años de experiencia.

In [5]:
import pandas as pd

empleados = {
    "Nombre": [
        "David Carcamo",
        "María López",
        "Carlos Méndez",
        "Ana Rodríguez",
        "José Rivera",
        "Sofía Hernández",
        "Luis Martínez",
        "Gabriela Flores"
    ],
    "Departamento": [
        "Tecnología",
        "Ventas",
        "Finanzas",
        "Recursos Humanos",
        "Tecnología",
        "Ventas",
        "Finanzas",
        "Tecnología"
    ],
    "Cargo": [
        "Desarrollador",
        "Vendedora",
        "Analista Financiero",
        "Coordinadora RRHH",
        "Administrador de Sistemas",
        "Supervisora de Ventas",
        "Contador",
        "Ingeniera de Software"
    ],
    "Salario": [
        35000,
        28000,
        32000,
        26000,
        40000,
        38000,
        30000,
        45000
    ],
    "AniosExperiencia": [
        3,
        6,
        4,
        8,
        10,
        7,
        5,
        9
    ],
    "Ciudad": [
        "Tegucigalpa",
        "San Pedro Sula",
        "La Ceiba",
        "Comayagua",
        "Danlí",
        "Tegucigalpa",
        "Juticalpa",
        "San Pedro Sula"
    ]
}

df_empleados = pd.DataFrame(empleados)

print("Primeros registros del DataFrame:")
display(df_empleados.head())

print("\nEstadísticas generales de salarios:")
display(df_empleados["Salario"].describe())

print("\nSalario promedio por departamento:")
display(df_empleados.groupby("Departamento")["Salario"].mean())

print("\nEmpleado con salario más alto:")
display(df_empleados.loc[[df_empleados["Salario"].idxmax()]])

print("\nEmpleados con más de 5 años de experiencia:")
display(df_empleados[df_empleados["AniosExperiencia"] > 5])

print("\nEmpleados ordenados por salario (de mayor a menor):")
display(df_empleados.sort_values(by="Salario", ascending=False))

def clasificar_experiencia(anios):
    if anios <= 2:
        return "Junior"
    elif anios <= 5:
        return "Intermedio"
    else:
        return "Senior"

df_empleados["NivelExperiencia"] = df_empleados["AniosExperiencia"].apply(
    clasificar_experiencia
)

print("\nDataFrame con la columna NivelExperiencia:")
display(df_empleados)

Primeros registros del DataFrame:

,Nombre,Departamento,Cargo,Salario,AniosExperiencia,Ciudad
0,David Carcamo,Tecnología,Desarrollador,35000,3,Tegucigalpa
1,María López,Ventas,Vendedora,28000,6,San Pedro Sula
2,Carlos Méndez,Finanzas,Analista Financiero,32000,4,La Ceiba
3,Ana Rodríguez,Recursos Humanos,Coordinadora RRHH,26000,8,Comayagua
4,José Rivera,Tecnología,Administrador de Sistemas,40000,10,Danlí

Estadísticas generales de salarios:

count        8.000000
mean     34250.000000
std       6475.227519
min      26000.000000
25%      29500.000000
50%      33500.000000
75%      38500.000000
max      45000.000000
Name: Salario, dtype: float64

Salario promedio por departamento:

Departamento
Finanzas            31000.0
Recursos Humanos    26000.0
Tecnología          40000.0
Ventas              33000.0
Name: Salario, dtype: float64

Empleado con salario más alto:

,Nombre,Departamento,Cargo,Salario,AniosExperiencia,Ciudad
7,Gabriela Flores,Tecnología,Ingeniera de Software,45000,9,San Pedro Sula

Empleados con más de 5 años de experiencia:

,Nombre,Departamento,Cargo,Salario,AniosExperiencia,Ciudad
1,María López,Ventas,Vendedora,28000,6,San Pedro Sula
3,Ana Rodríguez,Recursos Humanos,Coordinadora RRHH,26000,8,Comayagua
4,José Rivera,Tecnología,Administrador de Sistemas,40000,10,Danlí
5,Sofía Hernández,Ventas,Supervisora de Ventas,38000,7,Tegucigalpa
7,Gabriela Flores,Tecnología,Ingeniera de Software,45000,9,San Pedro Sula

Empleados ordenados por salario (de mayor a menor):

,Nombre,Departamento,Cargo,Salario,AniosExperiencia,Ciudad
7,Gabriela Flores,Tecnología,Ingeniera de Software,45000,9,San Pedro Sula
4,José Rivera,Tecnología,Administrador de Sistemas,40000,10,Danlí
5,Sofía Hernández,Ventas,Supervisora de Ventas,38000,7,Tegucigalpa
0,David Carcamo,Tecnología,Desarrollador,35000,3,Tegucigalpa
2,Carlos Méndez,Finanzas,Analista Financiero,32000,4,La Ceiba
6,Luis Martínez,Finanzas,Contador,30000,5,Juticalpa
1,María López,Ventas,Vendedora,28000,6,San Pedro Sula
3,Ana Rodríguez,Recursos Humanos,Coordinadora RRHH,26000,8,Comayagua

DataFrame con la columna NivelExperiencia:

,Nombre,Departamento,Cargo,Salario,AniosExperiencia,Ciudad,NivelExperiencia
0,David Carcamo,Tecnología,Desarrollador,35000,3,Tegucigalpa,Intermedio
1,María López,Ventas,Vendedora,28000,6,San Pedro Sula,Senior
2,Carlos Méndez,Finanzas,Analista Financiero,32000,4,La Ceiba,Intermedio
3,Ana Rodríguez,Recursos Humanos,Coordinadora RRHH,26000,8,Comayagua,Senior
4,José Rivera,Tecnología,Administrador de Sistemas,40000,10,Danlí,Senior
5,Sofía Hernández,Ventas,Supervisora de Ventas,38000,7,Tegucigalpa,Senior
6,Luis Martínez,Finanzas,Contador,30000,5,Juticalpa,Intermedio
7,Gabriela Flores,Tecnología,Ingeniera de Software,45000,9,San Pedro Sula,Senior